### ISSUE TITLE
RGB Led strip cant launch homebridge

### ISSUE THREAD

**Issue by aavela** [steve228uk/homebridge-magichome#32]
I'm getting this error 
when I set up an RGB configuration, the led is RGB and the controller is magichome 

it works if i set up with RGBWW but the colors and the configuration doesn't seem to match 

`events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51828
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:557:16)
    at Server.str.replace.Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:116:16)
    at Server.str.replace.Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:95:10)`

**Comment by Zacknetic** [comment]
What controller / bulb do you have. Always post your build so we know what we’re working with. RBG? RGBW? RGBWW? How many pins does it have ?

**Comment by aavela** [comment]
RGBW , 5 pins
