### ISSUE TITLE
config.json file

### ISSUE THREAD

**Issue by Hompe1** [steve228uk/homebridge-magichome#42]
I did everything that stood and got this, help? homebridge wont start because its a problem reading my config.json file

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-4-24 19:17:51] Loaded plugin: homebridge-config-ui
[2018-4-24 19:17:52] Registering platform 'homebridge-config-ui.config'
[2018-4-24 19:17:52] ---
[2018-4-24 19:17:52] Loaded plugin: homebridge-magichome
homebridge API version: 2.2
[2018-4-24 19:17:52] Registering accessory 'homebridge-magichome.MagicHome'
[2018-4-24 19:17:52] ---
[2018-4-24 19:17:52] There was a problem reading your config.json file.
[2018-4-24 19:17:52] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2018-4-24 19:17:52]
/usr/local/lib/node_modules/homebridge/lib/server.js:207
    throw err;
    ^

SyntaxError: Unexpected token : in JSON at position 13
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:201:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by isignedup** [comment]
https://jsonlint.com/

**Comment by Hompe1** [comment]
I tried that, but that did not help. so yeah:(
